[build]
  command = "npm run build:netlify"
  publish = "dist/quizmaster-pro/browser/browser"

[[plugins]]
  package = "@netlify/angular-runtime"
  
# Environment variables for build
[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_FLAGS = "--legacy-peer-deps"
