# Railway Backend Deployment Configuration

[build]
  builder = "nixpacks"

[build.env]
  NODE_VERSION = "20.19.0"

[deploy]
  startCommand = "npm start"
  
[env]
  NODE_ENV = "production"
  PORT = "4000"

# Environment variables (set these in Railway dashboard)
# DATABASE_URL=postgresql://postgres:WDjzRpZFbTSYsetmsemUYxCJbGKoWUzM@gondola.proxy.rlwy.net:45394/railway
# JWT_SECRET=railway-prod-jwt-secret-key-strong-32-chars-minimum-2025
# CORS_ORIGIN=https://your-frontend-domain.com

# Health check endpoint
healthCheckPath = "/api/health"

# Service configuration
[services.backend]
  buildCommand = "npm install"
  startCommand = "npm start"
  port = 4000
