# Railway Deployment Configuration for QuizMaster Pro Backend

[build]
builder = "nixpacks"

[build.env]
NODE_VERSION = "20.19.0"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
PORT = "4000"
HOST = "0.0.0.0"

# Set these environment variables in Railway Dashboard:
# DATABASE_URL=postgresql://postgres:WDjzRpZFbTSYsetmsemUYxCJbGKoWUzM@gondola.proxy.rlwy.net:45394/railway
# JWT_SECRET=railway-prod-jwt-secret-key-strong-32-chars-minimum-2025
# CORS_ORIGIN=https://quizmaster-pro-lemon.vercel.app
